# Generated by Django 4.1.7 on 2023-03-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceIcon', models.CharField(max_length=50)),
                ('serviceTitle', models.CharField(max_length=50)),
                ('serviceDesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testDesc', models.TextField()),
                ('testImg', models.FileField(default=None, max_length=250, null=True, upload_to='testImg/')),
                ('testName', models.CharField(max_length=50)),
            ],
        ),
    ]
