# Generated by Django 4.1.7 on 2023-03-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='testCompany',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
