# Generated by Django 4.1.7 on 2023-03-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_testimonials_testcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsImg', models.FileField(default=None, max_length=250, null=True, upload_to='testImg/')),
                ('newsHead', models.CharField(max_length=50)),
                ('newsDate', models.DateField(auto_now_add=True)),
                ('newsDesc', models.TextField()),
            ],
        ),
    ]
