# Generated by Django 4.1.7 on 2023-03-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newsImg',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='dateImg/'),
        ),
    ]
